### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by tinycat1917** [ProgregssTeam/GregFactory-Sky#16]
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.forgespi.language.IModFileInfo.getFile()" because the return value of "net.minecraftforge.fml.ModList.getModFileById(String)" is null
用2个漏斗把木桶夹在中间，然后漏小麦种子做泥土，会一直崩溃，进档就崩

**Comment by CPearl0** [comment]
已经在https://github.com/thedarkcolour/ExDeorum/pull/43 中修复，等待无中生有更新。
Fixed in https://github.com/thedarkcolour/ExDeorum/pull/43, wait for exdeorum's update.
