### ISSUE TITLE
利用Item filters使任务书可以检测流体

### ISSUE THREAD

**Issue by FakemanG** [ProgregssTeam/GregFactory-Sky#18]
这里以乙醇任务为例：
原先的任务检测只能检测到乙醇桶，而装有乙醇的GT大桶/单元/其他mod储罐无法被检测到
利用 **或过滤器** 和 **弱NBT过滤器**，将检测物品设置为 或过滤器，或过滤器的NBT设置为
{items:[{Count:1b,id:"itemfilters:weak_nbt",tag:{FluidName:"gtceu:ethanol"}},{Count:1b,id:"gtceu:ethanol_bucket"}]}
再将外观替换为乙醇桶的icon即可

**Comment by CPearl0** [comment]
Fixed in https://github.com/ProgregssTeam/GregFactory-Sky/commit/aa29059f22d2483257931aa69a1b773c67132a64
